apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gym-service.fullname" . }}
  labels:
    {{- include "gym-service.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ include "gym-service.name" . | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | default "INFO" | quote }}
  {{- if .Values.config.extraData }}
  {{- toYaml .Values.config.extraData | nindent 2 }}
  {{- end }}
