apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gym-service.fullname" . }}
  labels:
    {{- include "gym-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gym-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gym-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
