{{- if and .Values.istio.enabled .Values.istio.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ include "gym-service.fullname" . }}
  labels:
    {{- include "gym-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gym-service.selectorLabels" . | nindent 6 }}
  mtls:
    mode: {{ .Values.istio.peerAuthentication.mtlsMode }}
{{- end }}
