{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gym-service.fullname" . }}-secrets
  labels:
    {{- include "gym-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
