apiVersion: v1
kind: Service
metadata:
  name: {{ include "gym-service.fullname" . }}
  labels:
    {{- include "gym-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.service.metricsPort }}
    - port: {{ . }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "gym-service.selectorLabels" . | nindent 4 }}
